### ISSUE TITLE
magento/module-inventory-graph-ql dependency remaining

### ISSUE THREAD

**Issue by DmitryFurs** [yireo/magento2-replace-graphql#10]
After using `yireo/magento2-replace-graphql`, I see `magento/module-inventory-graph-ql` in the list of dependencies. I need the [inventory](https://github.com/magento/inventory) module and I can't use the [yireo/magento2-replace-inventory](https://github.com/yireo/magento2-replace-inventory/blob/master/composer.json#L30) dependency that excludes this extension, but I don't need the [Magneto_InventoryGraphQl](https://github.com/magento/inventory/tree/1.1-develop/InventoryGraphQl) module. I think that it should be replaced by this repository.

**Comment by jissereitsma** [comment]
This is simply a consequence of choosing to replace all GraphQL packages by using a meta-package, or all inventory packages by using a meta-package. If you disagree with how many packages are removed, simply copy the `replace` section of this meta-package to your own projects `composer.json`.

However, I think you are spot on to mention that all inventory packages should be replaced by the `replace-inventory` module just like the `replace-graphql` should replace all GraphQL modules. Unfortunately, if you install both, this leads to an error, which still needs to be resolved somehow. As of yet, there is no generic solution to this, except for simply replacing packages via your own `composer.json` (which was actually the whole point from where this initiative started).
