### ISSUE TITLE
Magento 2.3.4

### ISSUE THREAD

**Issue by DmitryFurs** [yireo/magento2-replace-graphql#11]
New dependencies added in 2.3.4:

- `magento/module-catalog-cms-graph-ql`
- `magento/module-catalog-customer-graph-ql`
- `magento/module-customer-downloadable-graph-ql`

**Comment by jissereitsma** [comment]
See https://github.com/yireo/magento2-replace-graphql/commit/7a673f6cd8eca8e4b70b40fbab86a4adac47bcb6
