### ISSUE TITLE
2.3.5-p1

### ISSUE THREAD

**Issue by fballiano** [yireo/magento2-replace-graphql#13]
Hi,
on M2.3.5-p1, when I try to install the module I get:

```
composer require yireo/magento2-replace-inventory:2.3.5
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yireo/magento2-replace-inventory 2.3.5 -> satisfiable by yireo/magento2-replace-inventory[2.3.5].
    - yireo/magento2-replace-inventory 2.3.5 requires magento/product-community-edition 2.3.5 -> satisfiable by magento/product-community-edition[2.3.5] but these conflict with your requirements or minimum-stability.
```

Same goes for the replace-inventory module :-)
Thanks!

**Comment by jissereitsma** [comment]
Currently, the two packages are not compatible with each other because they try to replace the same things. Just copy all of the replace entries from the one or the other to your own composer.json file.

**Comment by zamoroka** [comment]
Hi @jissereitsma 
looks the same for 2.3.3-p1 tag:
```
Problem 1
    - Can only install one of: magento/product-community-edition[2.3.3, 2.3.3-p1].
    - Can only install one of: magento/product-community-edition[2.3.3, 2.3.3-p1].
    - Can only install one of: magento/product-community-edition[2.3.3, 2.3.3-p1].
    - yireo/magento2-replace-graphql 2.3.3-p1 requires magento/product-community-edition 2.3.3 -> satisfiable by magento/product-community-edition[2.3.3].
    - Installation request for yireo/magento2-replace-graphql 2.3.3-p1 -> satisfiable by yireo/magento2-replace-graphql[2.3.3-p1].
    - Installation request for magento/product-community-edition (locked at 2.3.3-p1) -> satisfiable by magento/product-community-edition[2.3.3-p1].
```

and I believe, for all `-p*` versions. You need to delete those tags and make changes in the composer.json require section. 
so it should be like this: 
```
  "require": {
    "magento/product-community-edition": "2.3.3-p1"
  },
```

**Comment by jissereitsma** [comment]
Keeping the version numbers of this repository in line with the exact same version numbers of Magento is a big no-go. There are frequently updates to finetune the replacements and replacing the existing tags with new tags (with the same version number) would require an invalidation of the composer cache on every single instance where the replacements are used. So not a wise idea. (Even though I've been doing this myself for some time.)

A better idea would be to stick to semantic versioning - every tiny change should reflect in a version release as well (for instance, when changing the `require` section). Unfortunately, using patches (`-p1`) is known to be error-prone. Instead, in some other replace repos, I have switched to versioning where simply the `2` major is dropped in the Magento version to identify the version of this repo: So Magento version 2.3.3 replacements are kept in version 3.3.X of this repo, starting with 3.3.1. 

I've just released this, with the needed change (https://github.com/yireo/magento2-replace-graphql/blob/magento-2.3.3/composer.json#L4). Let me know if this is working for you.

**Comment by zamoroka** [comment]
Works, when using branch: ```composer require yireo/magento2-replace-graphql:dev-magento-2.3.3```
On tags - requirements still the same
Thanks :)

**Comment by jissereitsma** [comment]
When using tags, could you verify that you are using the `3.3.0` release? Because that's including the same as in the branch `magento-2.3.3` as of yet.

**Comment by zamoroka** [comment]
Oh, sorry didn't notice `3.3.0`. Yes, works great on 3.3.0 tag 
Thanks again.

**Comment by jissereitsma** [comment]
No worries. Unfortunately, it required a major bump. But good to hear the new procedure is working now.

**Comment by zamoroka** [comment]
Hi @jissereitsma 
Sorry for interrupting you, but seems to be the same issue for https://github.com/yireo/magento2-replace-inventory/blob/2.3.3-p1/composer.json

**Comment by jissereitsma** [comment]
Thanks. Quite a bit of work and worth a blog :) It is working now with the same new versioning strategy: https://github.com/yireo/magento2-replace-inventory/releases/tag/3.5.0 (and this also counts for all other replacement repos: `all` (combined), `core`, `content-staging`, `inventory`, `graphql` (this). Let me know if something is still bugging you.
