### ISSUE TITLE
Error with klarna/module-kp-graph-ql module

### ISSUE THREAD

**Issue by ocadmin81** [yireo/magento2-replace-graphql#17]
Hello,

After running the replace command  I'm getting the following error when trying to compile:

Uncaught Error: Interface 'Magento\QuoteGraphQl\Model\Cart\Payment\AdditionalDataProviderInterface' not found in /home/emanuel/domains/emanuelwallets.tempurl.co.il/public_html/vendor/klarna/module-kp-graph-ql/Model/KlarnaDataProvider.php:20
Stack trace:
#0 /home/emanuel/domains/emanuelwallets.tempurl.co.il/public_html/vendor/composer/ClassLoader.php(444): include()
#1 /home/emanuel/domains/emanuelwallets.tempurl.co.il/public_html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /home/emanuel/domains/emanuelwallets.tempurl.co.il/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
#5 /home/emanuel/domains/emanuelwallets.tempurl.co.il/public_html/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
#6 /home/emanuel/domains/emanuelwallets.tempurl.co.il in /home/emanuel/domains/emanuelwallets.tempurl.co.il/public_html/vendor/klarna/module-kp-graph-ql/Model/KlarnaDataProvider.php on line 20

I see here:
https://github.com/yireo/magento2-replace-graphql/blob/magento-2.4.0/composer.json#L8
That the module "klarna/module-kp-graph-ql" is not on the list of replace.
I added the line manually to composer.lock file:
"klarna/module-kp-graph-ql": "*"
To the list of modules.

I ran composer install and update but this did not help.

Thank you,
Eran

**Comment by jissereitsma** [comment]
Thanks for reporting this. First of all, it is correct to say that if you are removing the `magento/module-quote-graph-ql` package, any other package that is using its code, will be broken. I do NOT offer these packages as plug-and-play - I'm offering these packages for you to benefit from them, with the requirement that you dive into things as well. If you are removing GraphQL modules, I would say that is *nice* but the real benefit will be from removing the core bundled extensions as well (https://github.com/yireo/magento2-replace-bundled). Unfortunately, the replacement packages (in these repos) are complex to maintain, so there are reasons why you sometimes bump into issues when you are replacing A and B but not C, while C is relying on B. In short, replacing your own additional packages is common - just like you did already.

Either remove all Klarna modules, or remove only `klarna/module-kp-graph-ql`. 

You mention that you have edited the `composer.lock`. Please refer to the composer documentation which states you should **never** modify the `composer.lock` file directly. You can edit the `composer.json` file instead.

You also say you ran `composer install` and it didn't work. Please see the following documentation : https://github.com/yireo/magento2-replace-tools It explains that `composer install` indeed does not work. Also note that with `composer update`, chances are high that you will remove your own manual changes again. In short, do not edit the `composer.lock` file.

The documentation link above contains quite some hints on which commands do what. Take your time to go through them. I need you to experiment and learn as much about composer replacements, as I did before. This is experimental, and it requires that effort to benefit from it.

Let me know if you run into further issues.

**Comment by ocadmin81** [comment]
Hello

I installed also the bundled replace and the issue is resolved.

Thank you for your help!

**Comment by jissereitsma** [comment]
Cool to hear! Thanks for the update!
