### ISSUE TITLE
Missing Commerce modules

### ISSUE THREAD

**Issue by rikwillems** [yireo/magento2-replace-graphql#19]
Some Commerce modules are not in the list:

        "magento/module-catalog-rule-graph-ql": "*",
        "magento/module-catalog-staging-graph-ql": "*",
        "magento/module-catalog-permissions-graph-ql": "*",
        "magento/module-gift-message-graph-ql": "*",
        "magento/module-gift-wrapping-graph-ql": "*",
        "magento/module-multiple-wishlist-graph-ql": "*",
        "magento/module-newsletter-graph-ql": "*",
        "magento/module-review-graph-ql": "*",
        "magento/module-staging-graph-ql": "*",
        "magento/module-target-rule-graph-ql": "*",
        "magento/module-versions-cms-url-rewrite-graph-ql": "*",

**Comment by jissereitsma** [comment]
Happy to see PRs on this as well :) Would make life even easier. Anyway, changes are added here https://github.com/yireo/magento2-replace-graphql/commit/14b437e265248739a99e8d771f7926bc01ab508d and a new release is out as well https://github.com/yireo/magento2-replace-graphql/releases/tag/4.2.2 Thanks!

**Comment by rikwillems** [comment]
Thx @jissereitsma, next time you'll get a PR. Should have done that but was pressed for time a little and wanted to get it out anyway.
