### ISSUE TITLE
Magento_GraphQlCache

### ISSUE THREAD

**Issue by allrude** [yireo/magento2-replace-graphql#2]
is there a reason that this module doesn't get replaced?

**Comment by jissereitsma** [comment]
The module was added to 2.3.2 and should, therefore, be included in the `magento-2.3.2` release: https://github.com/yireo/magento2-replace-graphql/blob/magento-2.3.2/composer.json

**Comment by jissereitsma** [comment]
The `magento-2.3.2` branch is now merged into the `master` branch as well, so that the `master` branch always contains the latest changes.

**Comment by jissereitsma** [comment]
There is now a new release of the `2.3.2` tag - just to make sure. As far as I know, this should close this topic.
