### ISSUE TITLE
Replacement GraphQL package for Magento 2.4.7-p3

### ISSUE THREAD

**Issue by GianniPDF** [yireo/magento2-replace-graphql#28]
I was having some issues when compiling Magento 2.4.7-p3. In summary that some Interfaces were not found for these two packages:

magento/module-payment-services-paypal-graph-ql
magento/module-graph-ql-new-relic

I then added these two packages to my "replace" section in the composer.json

`...
"magento/module-payment-services-paypal-graph-ql": "*",
"magento/module-graph-ql-new-relic": "*",
...`

And now the setup:di:compile works.

The thing is, is this the right way to do it? 

If a want to add these changes to the repository, I need to create a pull request here?

I'm sorry, im just new to this kind of open source work etc.

**Comment by jissereitsma** [comment]
Thanks for spotting this. And yes, a PR for this would be the way. But to save you the trouble, I already made the change: https://github.com/yireo/magento2-replace-graphql/commit/7fda2e85b4c52fab122ff5908bfb384f6302c441 Thanks!
