### ISSUE TITLE
Magento 2.3.3.

### ISSUE THREAD

**Issue by simonmaass** [yireo/magento2-replace-graphql#4]
I believe the following modules have been added and also need to be removed:
module-related-product-graph-ql
module-paypal-graph-ql
module-checkout-agreements-graph-ql
module-braintree-graph-ql
module-authorizenet-graph-ql

**Comment by jissereitsma** [comment]
Added it https://github.com/yireo/magento2-replace-graphql/commit/4181be1d7e89c7d6f3359652ca2b629d255ac27f
